# Generated by Django 2.2.3 on 2019-07-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='favicon',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок'),
        ),
    ]
