# Generated by Django 2.2.3 on 2019-07-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_auto_20190724_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
